[package]
name = "lesson_2"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.5"
clap = { version = "4.5.24", features = ["derive"] }
csv = "1.3.1"
ed25519-dalek = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
